#!/usr/bin/env ruby

unless $:.include?(File.dirname(__FILE__) + "/../lib/")
  $: << File.dirname(__FILE__) + "/../lib"
end

require "sensu/run"

options = Sensu::Run.read_cli_opts

check = Sensu::Run::Check.new(options)
check.exec
event = check.event

api = Sensu::Run::APIClient.new(options)
api.post_event(event)
